"use client"

import { Button } from "@/components/ui/button"

interface ExportReportProps {
  edges: Array<{ source: string; target: string; weight: number }>
  mstEdges: number
  totalCost: number
  rejectedEdges: number
  disabled?: boolean
}

export default function ExportReport({ 
  edges, 
  mstEdges, 
  totalCost, 
  rejectedEdges,
  disabled = false 
}: ExportReportProps) {
  
  const generateReport = () => {
    const sortedEdges = [...edges].sort((a, b) => a.weight - b.weight)
    
    const report = `
╔════════════════════════════════════════════════════════════════╗
║           BÁO CÁO THUẬT TOÁN KRUSKAL - MST REPORT             ║
╚════════════════════════════════════════════════════════════════╝

📊 THỐNG KÊ TỔNG QUAN:
   • Tổng số đỉnh (V): ${new Set(edges.flatMap(e => [e.source, e.target])).size}
   • Tổng số cạnh (E): ${edges.length}
   • Cạnh trong MST: ${mstEdges}
   • Cạnh bị loại: ${rejectedEdges}
   • Tổng chi phí MST: ${totalCost}

📋 DANH SÁCH CẠNH (ĐÃ SẮP XẾP THEO TRỌNG SỐ):
${sortedEdges.map((e, i) => `   ${(i+1).toString().padStart(2, ' ')}. ${e.source} → ${e.target} (trọng số: ${e.weight})`).join('\n')}

🔬 PHÂN TÍCH ĐỘ PHỨC TẠP:
   • Sắp xếp cạnh: O(E log E) = O(${edges.length} × log ${edges.length})
   • Union-Find: O(E × α(V)) ≈ O(${edges.length})
   • Tổng độ phức tạp: O(E log E)

💡 KẾT LUẬN:
   Thuật toán Kruskal đã tìm được cây khung nhỏ nhất với ${mstEdges} cạnh
   và tổng trọng số là ${totalCost}. Đã xét ${edges.length} cạnh, trong đó
   ${rejectedEdges} cạnh bị loại vì tạo chu trình.

═══════════════════════════════════════════════════════════════════
Generated by Kruskal Visualizer | Đồ án Toán Rời Rạc
Student: Bùi Văn Chương | Date: ${new Date().toLocaleString('vi-VN')}
═══════════════════════════════════════════════════════════════════
`
    
    // Download as text file
    const blob = new Blob([report], { type: 'text/plain;charset=utf-8' })
    const url = URL.createObjectURL(blob)
    const link = document.createElement('a')
    link.href = url
    link.download = `Kruskal_Report_${new Date().getTime()}.txt`
    document.body.appendChild(link)
    link.click()
    document.body.removeChild(link)
    URL.revokeObjectURL(url)
  }

  return (
    <Button
      onClick={generateReport}
      disabled={disabled || edges.length === 0}
      className="w-full bg-linear-to-r from-purple-600 to-pink-600 hover:from-purple-500 hover:to-pink-500 text-white font-semibold shadow-lg hover:shadow-purple-500/50 transition-all duration-200"
    >
      📥 Xuất Báo Cáo (TXT)
    </Button>
  )
}
